### ISSUE TITLE
Kuradel

### ISSUE THREAD

**Issue by Ov3rlord286** [michael-gutman/konar-milestone-reminder#4]
After while guthix sleeps, duradel gets replaced by kuradel, and she isnt added to the list of slayer masters in the plugin so the reminder only pops up in chat, it doesnt highlight her or hide her

Same thing with Aya who replaces Turael after the same quest

**Comment by michael-gutman** [comment]
Thanks for the report! I thought I had fixed this, but I now see that the previous fix only worked if you reset the plugin. 
I've submitted a new update to the plugin hub that should make it work properly (without needing to reset): 
https://github.com/runelite/plugin-hub/pull/6468
